version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t dhaka-api .
      - docker tag dhaka-api:latest $ECR_REGISTRY/dhaka-api:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REGISTRY/dhaka-api:latest
      - echo Writing image definitions file...
      - printf '[{"name":"dhaka-api-container","imageUri":"%s"}]' $ECR_REGISTRY/dhaka-api:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json